export const TODO_LIST_LOAD = 'TODO_LIST_LOAD'
export const TODO_LIST_SAVE = 'TODO_LIST_SAVE'

export const TODO_LIST_ITEM_ADD = 'TODO_LIST_ITEM_ADD'
export const TODO_LIST_ITEM_CLEAR = 'TODO_LIST_ITEM_CLEAR'
export const TODO_LIST_ITEM_TITLE_CHANGED = 'TODO_LIST_ITEM_TITLE_CHANGED'
export const TODO_LIST_ITEM_TASK_CHANGED = 'TODO_LIST_ITEM_TASK_CHANGED'

export const TODO_LIST_ITEM_DELETE = 'TODO_LIST_ITEM_DELETE'
export const TODO_LIST_ITEM_COMPLETE = 'TODO_LIST_ITEM_COMPLETE'
